# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore NanoVG.Bindings
    - name: Build
      run: dotnet build --no-restore --configuration Release NanoVG.Bindings
    - name: Pack
      run: dotnet pack --configuration Release -p:PatchNumber=$GITHUB_RUN_NUMBER-pre NanoVG.Bindings
    - name: Move package to artifacts
      run: |
        mkdir artifacts
        find . -name \*.nupkg -exec mv {} artifacts/ \;
    - name: Publish to NuGet
      run: dotnet nuget push "artifacts/NanoVG.Bindings.*.nupkg" --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: artifacts
        path: artifacts/
